dist: xenial
env:
  global:
  - secure: |-
      IzTN2uuR4nsJ8+1IRmLXxn29+MK8PuKYgArbAU/aQPPm1vIUdMv0AYF/rq9N
      YBdJJqfUHwOcGBFuwX1oKp4ykb6VTdYGOOCAN0j3IWtDXMkFM+qSTsLishyw
      wSR11Z5SzTPxMGrY8cOupSH8mckmJvecomcYLctZdYwiP72+rSs=
addons:
  apt:
    update: true
    packages:
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-fonts-extra
      - texlive-fonts-recommended
      - texlive-lang-english
      - texlive-lang-italian
      - texlive-xetex
      - latexmk
      - python3-sphinx

# Travis runs ./gradlew assemble and ./gradlew check
# which, according to build.gradle, will run all
# jar, test and documentation tasks.
# See: 
#  - build.gradle
#  - https://docs.travis-ci.com/user/languages/java/
language: java 
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
after_success: 
  - bash <(curl -s https://codecov.io/bash)
  - ./utils/update-gh-pages.sh
